config/routes.rb
Rails.application.routes.draw do
  resources :ninjas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ninja.rb
class Ninja < ApplicationRecord
  validates :name, presence: true, length: { maximum: 75 }
  validates :guardian_name, presence: true, length: { maximum: 75 }
  validates :guardian_contact, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ninjas_controller.rb
class NinjasController < ApplicationController
  def index
    @ninjas = Ninja.all
  end

  def show
    @ninja = Ninja.find(params[:id])
  end

  def new
    @ninja = Ninja.new
  end

  def edit
    @ninja = Ninja.find(params[:id])
  end

  def create
    @ninja = Ninja.new(ninja_params)

    if @ninja.save
      redirect_to @ninja, notice: "Ninja was successfully created."
    else
      render :new
    end
  end

  def update
    @ninja = Ninja.find(params[:id])

    if @ninja.update(ninja_params)
      redirect_to @ninja, notice: "Ninja was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    ninja = Ninja.where(id: params[:id]).first

    if ninja.try(:destroy)
      redirect_to ninjas_url, notice: "Ninja was successfully destroyed."
    else
      redirect_to ninjas_url
    end
  end

  private

  def ninja_params
    params.require(:ninja).permit(:name, :guardian_name,
      :guardian_contact, :additional_information)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bokken
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/ninjas/_form.html.slim
= form_with(model: ninja, local: true) do |form|
  - if ninja.errors.any?
    #error_explanation
      h2
        = pluralize(ninja.errors.count, "error")
        | prohibited this ninja from being saved:
      ul
        - ninja.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :name, 'Nome'
    = form.text_field :name, placeholder: "Diogo Silva", id: :ninja_name
  .field
    = form.label :guardian_name, 'Nome encarregado de educação'
    = form.text_field :guardian_name, placeholder: "Pedro Silva",  id: :ninja_guardian_name
  .field
    = form.label :guardian_contact, 'Contacto encarregado de educação'
    = form.text_field :guardian_contact, placeholder: "pedro_silva@mail.com", id: :ninja_guardian_contact
  .field
    = form.label :additional_information, 'Informação adicional'
    = form.text_area :additional_information , placeholder: "Informação adicional", id: :ninja_additional_information
  .actions
    = form.submit

app/views/ninjas/edit.html.slim
h1 Editing Ninja
= render 'form', ninja: @ninja
= link_to 'Destroy', @ninja, method: :delete, data: { confirm: 'Are you sure?' }
| \
= link_to 'Back', ninjas_path

app/views/ninjas/index.html.slim
p#notice= notice
h1 Ninjas
= link_to 'New Ninja', new_ninja_path
table
  thead
    tr
      th Nome
  tbody
    - @ninjas.order('name').each do |ninja|
      tr
        td= link_to ninja.name, ninja
br/

app/views/ninjas/new.html.slim
h1 New Ninja
= render 'form', ninja: @ninja
= link_to 'Back', ninjas_path

app/views/ninjas/show.html.slim
p#notice= notice
p
  strong Nome:
  = @ninja.name
p
  strong Nome encarregado de educação:
  = @ninja.guardian_name
p
  strong Contacto encarregado de educação:
  = @ninja.guardian_contact
p
  strong Informação adicional:
  = @ninja.additional_information

= link_to 'Edit', edit_ninja_path(@ninja)
| \
= link_to 'Destroy', @ninja, method: :delete, data: { confirm: 'Are you sure?' }
| \
= link_to 'Back', ninjas_path